id: IF7FF91DD
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T05:14:02+00:00'
last_modified: '2022-06-08T16:42:15.598523+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN4594
  title: མངོན་བརྗོད་ཀྱི་བསྟན་བཅོས་མཁས་པའི་རྣ་རྒྱན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    1A06:
      image_group_id: I3CN4596
      title: ''
      total_pages: 218
      order: 1
      base_file: 1A06.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
